### ISSUE TITLE
Traceback (most recent call last):   error

### ISSUE THREAD

**Issue by mryldz** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#19]
I have rasspery pi zero,
I did everything as you show (set related step arm6l for rasperry pi zero only)
When I write the command "python3 Object_detection_picamera.py" I got these error.
How can I fix it.
Thanks.

```
pi@raspberrypi:~/tensorflow1/models/research/object_detection $ python3 Object_detection_picamera.py
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 84, in <module>
    serialized_graph = fid.read()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/pi/tensorflow1/models/research/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09/frozen_inference_graph.pb; No such file or directory
```

**Comment by leotardo** [comment]
hi 
i have the same Problem with my Pi zero, When i write the command "python3 Object_detection_picamera.py" i became follow error:
"illegal Instruction"

i tested on my Pi 3 and it works fine!

please how can i fix it... i need that for my project at the university. 

thanks 

![screenshot 2019-01-15 at 02 00 53](https://user-images.githubusercontent.com/46696049/51151131-d5da5880-1869-11e9-8ebb-d283372cd7b0.png)
