### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by wozwas** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#22]
Followed guide and everything looks good, but when I run python3 Object_detection_picamera.py I get the following:

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 23, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

**Comment by akhzarna** [comment]
I am also searching for the same issue, If you have fixed the issue please guide me

**Comment by Rambo-7** [comment]
I am also searching for the same issue, If you have fixed the issue please guide me too

**Comment by elektronika-ba** [comment]
Yep, me too.

**Comment by Rambo-7** [comment]
Could some masterminds help us ?😭

**Comment by Rambo-7** [comment]
I have solved this problem. Because there are some different editions of numpy in Pi. So uninstall other editions ,just keep one edition only.

**Comment by edgarscr** [comment]
> I have solved this problem. Because there are some different editions of numpy in Pi. So uninstall other editions ,just keep one edition only.

can u help me to fix?
