### ISSUE TITLE
File "/home/pi/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module> error

### ISSUE THREAD

**Issue by VictorTagayun** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#31]
This is my 2nd SD card having different error..
The [1st](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/issues/30) had a different error

```
pi@raspberrypi:~/tensorflow1/models/research/object_detection $ python3 Object_detection_picamera.py
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 23, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
```

**Comment by Evantm** [comment]
I had the same issue. You might be missing some dependencies, have you tried following the steps on this guide? https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

**Comment by VictorTagayun** [comment]
I did follow it and got these results

```
pi@raspberrypi:~ $ apt-file search libcblas.so.3
libatlas3-base: /usr/lib/atlas-base/libcblas.so.3
libatlas3-base: /usr/lib/atlas-base/libcblas.so.3.0
libatlas3-base: /usr/lib/libcblas.so.3
libcblas3: /usr/lib/arm-linux-gnueabihf/libcblas.so.3
libcblas3: /usr/lib/arm-linux-gnueabihf/libcblas.so.3.2.1
```

**Comment by tjcooperforted** [comment]
I also had the same issue of libjasper.so.1 in cv2 not being found.  I looked at the ..../cv2 directory and saw only one directory and there are supposed to be two.

So I looked at the "install" steps I had done and re-ran:
sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev

which had previously been done and showed no errors previously.
When it was done I had both directories and then Object_detection..... now worked perfectly.

So I believe you can do an install and have it fail to get all the libraries made.  Sometimes you have to 
do it twice.
   tjcooper
