### ISSUE TITLE
VIDIOC_REQBUFS: No such device

### ISSUE THREAD

**Issue by dedetuga** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#46]
Hi, I'm trying this on my raspberry pi however I'm getting some erros that I solver but this one I cannot see what is the problem.
So, I run this `pi@raspberrypi:~/tensorflow1/models/research/object_detection $ python3 Object_detection_picamera.py --usbcam`

and after a while I get the camera image, but 10 sec later I got an error: `pi@raspberrypi:~/tensorflow1/models/research/object_detection $ python3 Object_detection_picamera.py --usbcam
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
2019-05-16 09:51:51.406156: W tensorflow/core/framework/allocator.cc:124] Allocation of 8640000 exceeds 10% of system memory.
2019-05-16 09:51:52.530344: W tensorflow/core/framework/allocator.cc:124] Allocation of 8640000 exceeds 10% of system memory.
2019-05-16 09:51:53.278628: W tensorflow/core/framework/allocator.cc:124] Allocation of 8640000 exceeds 10% of system memory.
2019-05-16 09:51:54.004618: W tensorflow/core/framework/allocator.cc:124] Allocation of 8640000 exceeds 10% of system memory.
2019-05-16 09:51:54.737953: W tensorflow/core/framework/allocator.cc:124] Allocation of 8640000 exceeds 10% of system memory.
VIDIOC_DQBUF: No such device
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 192, in <module>
    feed_dict={image_tensor: frame_expanded})
  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
VIDIOC_REQBUFS: No such device`

The error is every time something _REQBUFS, I fond out if I lower the image sizer I can get this working very well but the problem is with an image size 150x150 I can not see nothing and all the fun is lost.

with a size 200x200 or high I got the error No such device
with a size 150x150 or low everything work great.

Why????
Any idea???
Its just me???
Can I solve it???

Thanks

**Comment by hktxt** [comment]
same problem, have u solved it?
