### ISSUE TITLE
Import error on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by biranchi2018** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#61]
$ python3 Object_detection_picamera.py --usbcam
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 51, in <module>
    from utils import label_map_util
  File "/home/pi/tensorflow/models/research/object_detection/utils/label_map_util.py", line 26, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

**Comment by biranchi2018** [comment]
Found solution in this thread [](https://github.com/tensorflow/models/issues/1595)
