### ISSUE TITLE
tf.gfile.GFile is deprecated.

### ISSUE THREAD

**Issue by maximlomans** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#70]
WARNING:tensorflow:From /home/pirate/Tensorflowed/models/research/object_detection/utils/label_map_util.py:138: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From Object_detection_picamera.py:82: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
^CTraceback (most recent call last):
  File "Object_detection_picamera.py", line 86, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/importer.py", line 494, in _import_graph_def_internal
    with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1080, in SerializeToString
    return self.SerializePartialToString(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1089, in SerializePartialToString
    self._InternalSerialize(out.write, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1109, in InternalSerialize
    field_descriptor._encoder(write_bytes, field_value, deterministic)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/encoder.py", line 760, in EncodeRepeatedField
    local_EncodeVarint(write, element.ByteSize(), deterministic)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1058, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/encoder.py", line 360, in FieldSize
    entry_msg = message_type._concrete_class(key=key, value=value)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 494, in init
    self._fields = {}
KeyboardInterrupt

**Comment by youngsandwhich** [comment]
Hey is there a solution to this?
