### ISSUE TITLE
Libmath Import Error 

### ISSUE THREAD

**Issue by shahran12** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#90]
I am getting this error when running the script. Checked everyting and followed all steps:
python3 Object_detection_picamera.py
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 23, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libImath-2_2.so.23: cannot open shared object file: No such file or directory

**Comment by LotfiT** [comment]
Hello, I have a similar issue, have you found a solution yet?
